name: Deploy lo to remote

on:
  pull_request:
    types: [merged]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote
        run: |
          echo "PR successfully merged"
